version: "3.9"

services:
  web:
    container_name: web_app
    build:
      context: services/web
      args:
        PHP_VERSION: ${PHP_VERSION:-8.2}
    volumes:
      - type: bind
        source: ./user/vhosts
        target: /etc/apache2/sites-enabled
      - type: bind
        source: ./services/web/docs
        target: /var/www/sites/app.local.com
      - ${VHOSTS_DIR:-~/www}:/var/www/vhosts
    working_dir: /var/www/sites/app.local.com
    ports:
      - ${WEB_HOSTNAME:-127.0.0.1}:${WEB_HOSTNAME_PORT:-80}:80
      - ${WEB_HOSTNAME:-127.0.0.1}:${NUXT_PORT:-3000}:3000
    tty: true
    stdin_open: true
    depends_on:
      - db
    env_file:
      - .env
    networks:
      app_network:
        ipv4_address: ${IPV4_NETWORK:-172.25.2}.10
        aliases:
          - application

  db:
    container_name: web_app_db
    # force x86_64 architecture when running on a different platform
    platform: linux/x86_64
    build:
      context: services/mysql
    ports:
      - ${DATABASE_HOST:-127.0.0.1}:${DATABASE_HOST_PORT:-3306}:3306
    volumes:
      - type: bind
        source: ./user/mysql.conf.d
        target: /etc/mysql/mysql.conf.d/
      - type: bind
        source: ./services/mysql/etc/mysql/conf.d/
        target: /etc/mysql/conf.d/
      - data:/var/lib/mysql/
    env_file:
      - .env
    networks:
      app_network:
        ipv4_address: ${IPV4_NETWORK:-172.25.2}.11
        aliases:
          - database

  redis:
    container_name: web_app_redis
    build:
      context: services/redis
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - ./services/redis/redis.conf:/etc/redis.conf
      - redis:/storage
    networks:
      app_network:
        ipv4_address: ${IPV4_NETWORK:-172.25.2}.12
        aliases:
          - redis_store

volumes:
  data:
    driver: local
  redis:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./user/data/redis"

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.25.2}.0/24
          gateway: ${IPV4_NETWORK:-172.25.2}.1
